language: java

before_install:
  - ./install_dependencies.sh
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install: mvn install

notifications:
  email:
    on_success: never

# whitelist
branches:
  only:
    - master
    - develop

after_success:
  - mvn clean cobertura:cobertura coveralls:report