package com.tagmycode.plugin.gui.form;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import com.tagmycode.plugin.Framework;
import com.tagmycode.plugin.gui.AbstractGui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class LoginPanel extends AbstractGui {
    private JButton loginButton;
    private JPanel mainPanel;
    private JButton aboutButton;

    public LoginPanel(final Framework framework) {
        loginButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                framework.showLoginDialog();
            }
        });
        aboutButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                framework.showAboutDialog();
            }
        });

    }

    @Override
    public JComponent getMainComponent() {
        return mainPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new FormLayout("fill:d:grow", "center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:d:grow"));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        CellConstraints cc = new CellConstraints();
        mainPanel.add(panel1, cc.xy(1, 3, CellConstraints.LEFT, CellConstraints.DEFAULT));
        loginButton = new JButton();
        loginButton.setHorizontalAlignment(2);
        loginButton.setIcon(new ImageIcon(getClass().getResource("/icons/signin.png")));
        loginButton.setText("Login...");
        panel1.add(loginButton);
        aboutButton = new JButton();
        aboutButton.setIcon(new ImageIcon(getClass().getResource("/icons/help.png")));
        aboutButton.setText("");
        aboutButton.setToolTipText("About...");
        panel1.add(aboutButton);
        final JToolBar toolBar1 = new JToolBar();
        toolBar1.setFloatable(false);
        mainPanel.add(toolBar1, cc.xy(1, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label1 = new JLabel();
        label1.setIcon(new ImageIcon(getClass().getResource("/images/tagmycode_logo.png")));
        label1.setText("");
        toolBar1.add(label1);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
