package com.tagmycode.plugin.gui.form;

import com.tagmycode.plugin.Framework;
import com.tagmycode.plugin.gui.AbstractGui;
import com.tagmycode.plugin.gui.IAbstractGUI;

import javax.swing.*;
import java.awt.*;

public class MainWindow implements IAbstractGUI {
    private final SnippetsPanel snippetsPanel;
    private final LoginPanel loginPanel;
    private JPanel mainPanel;
    private boolean networkingEnabled;

    public MainWindow(final Framework framework) {
        snippetsPanel = new SnippetsPanel(framework);
        loginPanel = new LoginPanel(framework);
    }

    public void setLoggedIn(boolean flag) {
        getMainComponent().removeAll();
        AbstractGui component = flag ? snippetsPanel : loginPanel;
        if (component instanceof SnippetsPanel) {
            ((SnippetsPanel) component).reset();
        }
        getMainComponent().add(component.getMainComponent());
        getMainComponent().revalidate();
        getMainComponent().repaint();
    }

    @Override
    public JComponent getMainComponent() {
        return mainPanel;
    }

    public SnippetsPanel getSnippetsPanel() {
        return snippetsPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
