package com.tagmycode.plugin.gui.form;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import com.tagmycode.plugin.FileSize;
import com.tagmycode.plugin.Framework;
import com.tagmycode.plugin.gui.GuiUtil;
import com.tagmycode.sdk.DateParser;
import com.tagmycode.sdk.model.Snippet;

import javax.swing.*;
import java.awt.*;
import java.nio.charset.StandardCharsets;
import java.text.DateFormat;
import java.util.Date;
import java.util.Locale;

public class PropertiesForm extends Windowable {
    private JButton buttonCancel;
    private JPanel contentPane;
    private JTextField snippetTitle;
    private JTextField snippetUrlTextField;
    private JCheckBox privateCheckBox;
    private JTextField codeSizeTextField;
    private JTextField modifiedAtTextField;
    private JTextField createdAtTextField;
    private JTextField languageTextField;
    private JCheckBox synchronizedCheckBox;
    private Snippet snippet;

    PropertiesForm(Framework framework, Snippet snippet) {
        super(framework, framework.getParentFrame());
        this.snippet = snippet;
        defaultInitWindow();
        initWindow();
        populateFields();
    }

    private void populateFields() {
        setTitle(snippet.getTitle());
        snippetTitle.setText(snippet.getTitle());
        languageTextField.setText(snippet.getLanguage().getName());
        createdAtTextField.setText(dateAndTime(snippet.getCreationDate()));
        modifiedAtTextField.setText(dateAndTime(snippet.getUpdateDate()));
        snippetUrlTextField.setText(snippet.getUrl());
        int bytes = snippet.getCode().getBytes(StandardCharsets.UTF_8).length;
        codeSizeTextField.setText(FileSize.toHumanReadable(bytes));
        privateCheckBox.setSelected(snippet.isPrivate());
        synchronizedCheckBox.setSelected(!snippet.isDirty());
    }

    private String dateAndTime(Date date) {
        return new DateParser(date).toDateTimeLocale(DateFormat.SHORT, DateFormat.MEDIUM, Locale.getDefault());
    }

    @Override
    protected void initWindow() {
        JTextField[] jTextFields = new JTextField[]{snippetTitle, languageTextField, createdAtTextField,
                modifiedAtTextField, codeSizeTextField, snippetUrlTextField};
        for (JTextField field : jTextFields) {
            GuiUtil.makeTransparentTextField(field);
            field.setEditable(false);
        }

        setSize(450, 350);
        setResizable(true);
    }

    @Override
    protected void onOK() {

    }

    @Override
    public JButton getButtonOk() {
        return new JButton();
    }

    @Override
    protected JButton getButtonCancel() {
        return buttonCancel;
    }

    @Override
    public JComponent getMainComponent() {
        return contentPane;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FormLayout("fill:d:noGrow,left:4dlu:noGrow,fill:d:grow", "center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        panel1.add(panel2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Language:");
        CellConstraints cc = new CellConstraints();
        panel2.add(label1, cc.xy(1, 3));
        final JLabel label2 = new JLabel();
        label2.setText("Modified at:");
        panel2.add(label2, cc.xy(1, 7));
        final JLabel label3 = new JLabel();
        label3.setText("Created at:");
        panel2.add(label3, cc.xy(1, 5));
        final JLabel label4 = new JLabel();
        label4.setText("Code size:");
        panel2.add(label4, cc.xy(1, 9));
        final JLabel label5 = new JLabel();
        label5.setText("Snippet url:");
        panel2.add(label5, cc.xy(1, 11));
        final JLabel label6 = new JLabel();
        label6.setText("Private snippet:");
        panel2.add(label6, cc.xy(1, 13));
        privateCheckBox = new JCheckBox();
        privateCheckBox.setEnabled(false);
        privateCheckBox.setText("");
        panel2.add(privateCheckBox, cc.xy(3, 13));
        codeSizeTextField = new JTextField();
        panel2.add(codeSizeTextField, cc.xy(3, 9, CellConstraints.FILL, CellConstraints.DEFAULT));
        modifiedAtTextField = new JTextField();
        panel2.add(modifiedAtTextField, cc.xy(3, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
        createdAtTextField = new JTextField();
        panel2.add(createdAtTextField, cc.xy(3, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        languageTextField = new JTextField();
        panel2.add(languageTextField, cc.xy(3, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label7 = new JLabel();
        label7.setText("Synchronized:");
        panel2.add(label7, cc.xy(1, 15));
        synchronizedCheckBox = new JCheckBox();
        synchronizedCheckBox.setEnabled(false);
        synchronizedCheckBox.setText("");
        panel2.add(synchronizedCheckBox, cc.xy(3, 15));
        final JLabel label8 = new JLabel();
        label8.setText("Title:");
        panel2.add(label8, cc.xy(1, 1));
        snippetTitle = new JTextField();
        panel2.add(snippetTitle, cc.xy(3, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FormLayout("fill:d:grow", "center:d:grow"));
        panel2.add(panel3, cc.xy(3, 11, CellConstraints.FILL, CellConstraints.DEFAULT));
        snippetUrlTextField = new JTextField();
        panel3.add(snippetUrlTextField, cc.xy(1, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(panel4, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, 1, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel4.add(spacer1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel4.add(panel5, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        buttonCancel = new JButton();
        buttonCancel.setText("Close");
        panel5.add(buttonCancel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
